name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --release

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./target/release/conag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}